# import turtle
from turtle import *
screen = Screen()
pen = Turtle()
pen.forward(200)
pen.right(90)
pen.forward(100)
pen.right(90)
pen.forward(200)
pen.right(90)
pen.forward(100)
pen.shape('turtle')
pen.fillcolor('blue')
pen.color('red')
done()